### ISSUE TITLE
Android null pointer exception

### ISSUE THREAD

**Issue by shinyford** [rmawatson/flutter_isolate#12]
Hi

First off, let me just say that I've been looking for something like this for ages. Isolates are, IMHO, virtually unusable without it, so thanks hugely.

Secondly: it's working well for me on iOS, but on Android I repeatedly hit the following null pointer exception:

```E/FlutterIsolate(15785): NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
E/FlutterIsolate(15785): It is possible the default GeneratedPluginRegistrant is attempting to register
E/FlutterIsolate(15785): a plugin that uses registrar.activity() or a similar method. Flutter Isolates have no
E/FlutterIsolate(15785): access to the activity() from the registrant. If the activity is being use to register
E/FlutterIsolate(15785): a method or event channel, have the plugin use registrar.context() instead. Alternatively
E/FlutterIsolate(15785): use a custom registrant for isolates, that only registers plugins that the isolate needs
E/FlutterIsolate(15785): to use.
```

I can see that you've introduced a custom registrant through the commits; but I wonder if it's working as expected? (Sorry to not be more helpful - this is not my area of expertise.)

Anything that can be done to fix this would be very gratefully received.

Cheers

Nic

**Comment by rmawatson** [comment]
Nic, what the plugin your trying to get working with this?

The message your seeing is usually because the specific plugin that your registering is using registrar.activity() when it registers itself with flutter, which is not available during the registration when using a 'FlutterIsolate'. 

Depending on the plugin, it's often the case that it doesn't actually need an activity, but a context will do. For example, see the changes I had to make to FlutterBlue [here] (https://github.com/rmawatson/flutter_blue/commit/28ca4e215da7eb24ecfa88bb2ebd59759811f806), using context() instead of activity(), as everywhere in this plugin activity() was used, a context() was sufficient.

The reason for the custom registrant is that in both iOS and Android, flutter auto generates the GeneratedPluginRegistrant based on what plugins your using in your pubspec.yaml. FlutterIsolate uses this for registering all the plugins with itself. 

The problem, it can't pick and choose. It will be all or nothing, and some plugins may very well need to use an activity() in their registration which will cause the above error. 

The idea of using a CustomPluginRegistrant is that you can manually specify which plugins will be registered for use with FlutterIsolate, so it can be only the ones you actually want to use in the FlutterIsolate. Usually this is maybe one or two of the 20 plugins your using in your project.

If you've tested all this and it turns out not to be the problem I can try and have a look with the plugin you're trying to use.

**Comment by shinyford** [comment]
Hi - apologies for the late reply, and thanks for the very full explanation.

Specifically I was trying to use two plugins: `flutter_native_image` and `firebase_storage`. I'll take a look at those two, to see if forking and replacing `activity`s with `context`s is a possibility. I'll let you know how it goes, and if anything else needs to be looked at.

Cheers!

Nic

**Comment by shinyford** [comment]
Okay - so, I've removed `flutter_native_image` from the equation, leaving only `firebase_storage`. That looks like it already uses a `context` rather than an activity: 

```
  private FirebaseStoragePlugin(MethodChannel channel, Registrar registrar) {
    this.channel = channel;
    FirebaseApp.initializeApp(registrar.context());
  }
```
and I can find no reference to an `activity` anywhere in the java code within that package. Nonetheless, the null pointer error is occuring when I try to push an image to Firebase storage using `ref.putFile`. 

Any insights gratefully received. Thanks for taking a look - I'd love to be able to use an isolate here.

**Comment by rmawatson** [comment]
Have you looked at the call stack to see how/when this is being called?

without any context it's hard to say.

**Comment by BeDaut** [comment]
@rmawatson 
Hello, your library is awesome but I have the same warning:
```
E/FlutterIsolate(18567): NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/FlutterIsolate(18567): It is possible the default GeneratedPluginRegistrant is attempting to register
E/FlutterIsolate(18567): a plugin that uses registrar.activity() or a similar method. Flutter Isolates have no
E/FlutterIsolate(18567): access to the activity() from the registrant. If the activity is being use to register
E/FlutterIsolate(18567): a method or event channel, have the plugin use registrar.context() instead. Alternatively
E/FlutterIsolate(18567): use a custom registrant for isolates, that only registers plugins that the isolate needs
E/FlutterIsolate(18567): to use.
```

as I get from your message it's because I use [camera plugin](https://pub.dev/packages/camera) and [url launcher plugin](https://pub.dev/packages/url_launcher) - both of them use `activity()`

So, without forking and fixing those libraries myself (if they really don't need `activity()` and can get by just 'context()') I would get this message every time I spawn isolate, am I understanding this correctly?

**Comment by rmawatson** [comment]
Yes,  you will likely not be able to use `camera plugin` in the background. Never used this but It probably relies on having an `activity` - this is just a guess. If you are trying to use *something else* in the background, but its failing on `camera plugin`, by default for each `flutter_isolate` started, all plugins that the main application isolate is using will (try to) be loaded. This is done by the auto generated `GeneratedPluginRegistrant` by Flutter. This means if you have plugins that use `activity()` the loading will fail. 

However if you only actually need to use some specific plugin in the background, something that is likely to work (ie, doesn't need an `Activity`) you can use a `CustomPluginRegistrant`. This is basically a copy and paste of the `GeneratedPluginRegistrant` that flutter creates, where you have removed unneeded plugins from the list of plugins to load, and in the native code you register this with the FlutterIsolate plugin. It's a few lines of code for ios and android.

This way you can avoid your background plugin loading anything that uses `activity()` and that you don't need available in the background isolate.

Does that make sense?

**Comment by BeDaut** [comment]
Thanks for the fast response! :)

I'm using video from camera plugin and sending some frames to backend, but before sending I'm cropping and compressing them - it causes stutters in the UI. These operations (cropping and compressing) I'm trying to put in isolate.

Sorry, I'm not at work currently and can't show examples of code, I can provide them if you need tomorrow.

I'm able to use camera in the background, it just prints some warnings in the console.

I'm guessing that since I need camera I'll get those warnings anyway.

**Comment by allenbrunson** [comment]
i am in the same boat: probably 20 plugins, i only need two or three in background isolates, crashes during registration.

you say it's only a few lines of code to write a CustomPluginRegistrant, but i have no idea how to do that. googling has not helped. maybe update the docs for those of us who have never done that before?

**Comment by nmfisher** [comment]
The README now has examples showing how to register a CustomPluginRegistrant, please open a new issue if anything remains unclear.

**Comment by Okiring** [comment]
I tried this example but still get the same issue. Path provider cannot be found

MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
