### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The method 'toRawHandle' was called on null.

### ISSUE THREAD

**Issue by MichealReed** [rmawatson/flutter_isolate#18]
I am trying to use isolates to initiate a bluetooth and socket connection from inside a bloc. When I try from main, I do not receive this error, but for some reason I am getting this NoSuchMethodError. It may be the fact that I am calling the isolate from a stream. Any thoughts?

![image](https://user-images.githubusercontent.com/12153323/62476028-de45a280-b76b-11e9-88c1-62165efc896c.png)

**Comment by MichealReed** [comment]
I found this issue in the background repo, but I don't quite understand how to apply the solution here.

https://github.com/transistorsoft/flutter_background_fetch/issues/26

**Comment by rmawatson** [comment]
The problem lies with 
``` 
final userEntryPointId =
        PluginUtilities.getCallbackHandle(entryPoint).toRawHandle();
```

This `userEntryPointId` here is a handle is passed to android/ios and used for launching the isolate with the native stuff. 

`PluginUtilities` is part of `dart:isolate` I think, or one of the other packages I import in `flutter_isolate.dart`. 

You can try and import it yourself and see why `PluginUtilities.getCallbackHandle(isoalte2)` is returning `null`. 

is it possible you are using an instance method? This is the same error [here](https://github.com/flutter/engine/pull/6260). Hard to say from yourscreenshot. But at a glance it doesn't look like it.

**Comment by MichealReed** [comment]
Thanks for pointing me in the right direction. `PluginUtilities.getCallbackHandle()` requires a static or top-level function to work. Simply adding static in front of my isolate function worked well.

More info:
https://stackoverflow.com/questions/54149840/flutter-android-alarm-manager-not-working

**Comment by rmawatson** [comment]
awesome, glat that sorted it!
