### ISSUE TITLE
Type 'FlutterIsolatePlugin' has no member 'isolatePluginRegistrantClassName'

### ISSUE THREAD

**Issue by sikandernoori** [rmawatson/flutter_isolate#84]
I am getting below error when I build App.

My Appdelegate.swift file looks like this.

```
import UIKit
import Flutter
import flutter_downloader
import flutter_isolate

// Defines a custom plugin registrant, to be used specifically together with FlutterIsolatePlugin
@objc(IsolatePluginRegistrant) class IsolatePluginRegistrant: NSObject {
    @objc static func register(withRegistry registry: FlutterPluginRegistry) {
        // Register channels for Flutter Isolate
        initswiftyTesseract(bm: registry.registrar(forPlugin: "com.hunaindev.flutter_tesseract").messenger())

        // Register default plugins
        GeneratedPluginRegistrant.register(with: registry)
    }
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

        let controller = window.rootViewController as! FlutterViewController

        // Register custom channels for Flutter
        // initswiftyTesseract(bm: controller.binaryMessenger) // <-- the custom method channel

        // Point FlutterIsolatePlugin to use our previously defined custom registrant.
        // The string content must be equal to the plugin registrant class annotation 
        // value: @objc(IsolatePluginRegistrant)
        FlutterIsolatePlugin.isolatePluginRegistrantClassName = "IsolatePluginRegistrant" // <--


    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) { 
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
       FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
    }
}
```

**Comment by nmfisher** [comment]
@sikandernoori which version of the plugin are you trying to run?

**Comment by sikandernoori** [comment]
@nmfisher 
`flutter_isolate: ^2.0.0`

**Comment by nmfisher** [comment]
If you want to use a custom plugin registrant, you'll need to use `2.0.1-pre`.

Are you sure you need to use a custom plugin registrant?

**Comment by abhinavsingh** [comment]
> 2.0.1-pre

I am wondering what's the stability of `2.0.1-pre`.  Any specific reason why it's a pre-release and haven't turned into a proper release yet?  Our application includes an in-house call module, which internally performs audio routing setup and other initialization.  Unfortunately, isolate seems to load this call plugin _(unused by isolate)_, resulting into dual setup and app crashes.

Copying below code ran straight into `registerMethodChannelABC` not found in scope.  Looks like this has been deprecated.

```
// Defines a custom plugin registrant, to be used specifically together with FlutterIsolatePlugin
@objc(IsolatePluginRegistrant) class IsolatePluginRegistrant: NSObject {
  @objc static func register(withRegistry registry: FlutterPluginRegistry) {
    // Register channels for Flutter Isolate
    registerMethodChannelABC(bm: registry.registrar(forPlugin: "net.myapp.myChannelABC").messenger())

    // Register default plugins
    GeneratedPluginRegistrant.register(with: registry)
  }
}
```

The code within `AppDelegate.m` from examples folder doesn't seem to call `GeneratedPluginRegistrant.register(with: self)` at all, so I am wondering does it even load other configured plugins in the environment.  Or is the example turned for specific plugins used by the example code.

Any pointers will be helpful.  Thank you!!!

**Comment by nmfisher** [comment]
@abhinavsingh  if you're using a custom plugin registrant, then `GeneratedPluginRegistrant` is ignored. The example project is intended to show the use of the FlutterDownloader and PathProvider plugins via a custom registrant - you'll see that everything is handled by `IsolatePluginRegistrant`. As a consequence, if you added/removed plugins to/from this project, you'd need to manually add/delete the plugins registrations yourself. You won't be able to rely on the auto-generated list in `GeneratedPluginRegistrant`.

This functionality is needed because _some_ plugins will try to re-register themselves when called inside an isolate. This can break things (e.g. method channels being overridden), which is why we need some way of interjecting ourselves into the plugin registration process. For example, you can see the custom `IsolatePluginRegistrant` has a check for the existence of FlutterDownloaderPlugin before registering itself and a similar registration callback (from memory, if you comment out this check, something will break).

`registerMethodChannelABC` is just a placeholder, the docs need to be edited to be clear you'll need to write this yourself if you need to register your own method channel. Whether or not you need to register your own method channel will depend on the plugin you're trying to register (for example, if you want a separate method channel per isolate).

From the sounds of it, your external audio plugin is breaking in a similar way - presumably trying to reregister itself when called from within an isolate. I'd suggest duplicating the functionality in `AppDelegate.m` (replacing `FlutterDownloaderPlugin`  and `FLTPathProviderPlugin` with your own plugins as needed), and ignoring the method channel registration for the time being. If you're still experiencing issues, leave a note here and am happy to help with the method channel.

**Comment by abhinavsingh** [comment]
@nmfisher After some deep dive and investigation, we have come to a conclusion that proposed solution is not tenable.

a) It requires manual fiddling of plugin registrant, which is both error prone and a maintenance overhead, specially in a large team scenario with ton's of plugins.

b) I am not entirely sure if it even resolves the issue.  Instead of going into `AppDelegate`, I simply modified plugin registrant and wrapped the offending plugin around `if(![registry hasPlugin:@"MyPlugin"]) {` block, but app still ran into double initialization.  Which forced me to think how will `if(![registry hasPlugin:@"MyPlugin"]) {` even help if `registry` instances are not the same between the main app and the isolate?  Please correct me if wrong.

We are planning to re-architecture the app and remove dependency over isolates.  When we started using `flutter_isolate` for background tasks `(contact parsing/syncing)`, we didn't had our in-house plugin, which now have started running into double initialization and crashes because of isolates.  This is specially a problem when app is in the terminated state, and user opens the app via an intent (e.g. clicking a notification).  At this point, our app also needs audio routing from in-house plugin and it also starts contact syncing via isolate, running into double initialization and immediate crashes.
